function [ inth9,inth10]=expikrr(k1,k2,k3)
h1=@(x,u,w) (pi^2*(cos((k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+cos((k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+cos((k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
    + pi^2*(cos((k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+cos((k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+cos((k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 +pi^2*(cos((k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+cos((k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+cos((k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(cos((k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+cos((k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+cos((k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))...
+ pi^2*(cos((-k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+cos((-k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+cos((-k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
 + pi^2*(cos((-k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+cos((-k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+cos((-k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 + pi^2*(cos((-k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+cos((-k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+cos((-k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(cos((-k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+cos((-k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+cos((-k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))).*x./(1+u.^2+w.^2).^(1/2);
 inth9=integral3(h1,0,1,0,1,0,1,'AbsTol',1e-6)
 h2=@(x,u,w) (pi^2*(sin((k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+sin((k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+sin((k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
    + pi^2*(sin((k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+sin((k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+sin((k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 +pi^2*(sin((k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+sin((k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+sin((k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(sin((k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+sin((k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+sin((k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))...
+ pi^2*(sin((-k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+sin((-k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+sin((-k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
 + pi^2*(sin((-k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+sin((-k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+sin((-k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 + pi^2*(sin((-k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+sin((-k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+sin((-k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(sin((-k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+sin((-k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+sin((-k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))).*x./(1+u.^2+w.^2).^(1/2);
 inth10=integral3(h2,0,1,0,1,0,1,'AbsTol',1e-6)